config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :departments do
    member do
      get :tasks
    end
  end
  
  resources :users do
    member do
      get :tasks
    end
  end
  
  resources :tasks do
    member do
      patch :assign
    end
    resources :comments, only: [:create]
  end
  
  root 'tasks#index'
  
  # Add some useful routes for dashboard
  get 'dashboard', to: 'tasks#dashboard'
  get 'my_tasks', to: 'tasks#my_tasks'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project Management System</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <nav class="main-nav">
        <div class="nav-container">
          <div class="nav-brand">
            <%= link_to 'Project Manager', root_path, class: 'brand-link' %>
          </div>
          
          <div class="nav-menu">
            <%= link_to 'Dashboard', dashboard_path, class: 'nav-link' %>
            <%= link_to 'Tasks', tasks_path, class: 'nav-link' %>
            <% if current_user.admin? || current_user.manager? %>
              <%= link_to 'Departments', departments_path, class: 'nav-link' %>
            <% end %>
            <% if current_user.admin? %>
              <%= link_to 'Users', users_path, class: 'nav-link' %>
            <% end %>
          </div>
          
          <div class="nav-user">
            <span class="user-info">
              <%= current_user.name %> (<%= current_user.role.humanize %>)
            </span>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link sign-out' %>
          </div>
        </div>
      </nav>
    <% end %>

    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert"><%= flash[:alert] %></div>
    <% end %>

    <%= yield %>
  </body>
</html>